name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "file:./prisma/dev.db"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "ci-secret-32-character-random-key-12345"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies (Strict lockfile check)
        run: npm ci --legacy-peer-deps

      - name: Dependency Vulnerability Audit
        run: npm audit --audit-level=high

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Build Next.js
        run: npm run build
